api_version: v1
data:
  apps:  apps.yaml
  categories: categories.yaml
schemas:
  apps: src/static/schemas/v2/apps.schema.json
  categories: src/static/schemas/v2/categories.schema.json
  apps_meta: src/static/schemas/v2/apps_meta.schema.json
  metadata: src/static/schemas/v2/metadata.schema.json
build:
  html: src/build/html
  static_src: src/static
