api_version: v1
data:
  apps:  apps.yaml
  categories: categories.yaml
schemas:
  path: src/static/schemas/v1
environments:
  cmd: "repo2env --dirs .aiidalab/ --dirs ./ "
build:
  html: src/build/html
  static_src: src/static
