openapi: 3.0.1
info:
  title: AiiDAlab apps registry API
  description: API to query for registered AiiDAlab apps.
  version: '0.2'
servers:
  - url: 'https://aiidalab.github.io/aiidalab-registry'
paths:
  /apps_meta.json:
    get:
      description: Full index and metadata for all apps.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: https://aiidalab.github.io/aiidalab-registry/schemas/v1/apps_meta.schema.json#/definitions/Welcome
  /api/v1/{appId}.metadata.json:
    parameters:
    - name: appId
      in: path
      required: true
      schema:
        type: string
    get:
      description: The fully resolved metadata for app with appId.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: https://aiidalab.github.io/aiidalab-registry/schemas/v2/metadata.schema.json#/definitions/Welcome